### ISSUE TITLE
Device not found

### ISSUE THREAD

**Issue by mcasper73** [doudz/homeassistant-myjdownloader#2]
Hy, thank you for your effort. I configured your integration but the sensor state is device not found. I use regularly myjdownloader extension on chrome. 
Thank you for your reply.

**Comment by doudz** [comment]
Are you using the latest commit ? There was a bug before #1

**Comment by mcasper73** [comment]
I think so. I have e94859a version.

**Comment by doudz** [comment]
:thinking:

**Comment by mcasper73** [comment]
I solved. I don't use name field and now i can find correct sensor state.

- platform: myjdownloader
  email: !secret mjd_user
  password: !secret mjd_pwd
#  name: MyJD

Thanks.

**Comment by doudz** [comment]
Did you wait enough ? default scan interval is 60 sec

**Comment by mcasper73** [comment]
Please read above. I edit my comment.

**Comment by doudz** [comment]
name is somethink like `MyJDownloader@user`

**Comment by mcasper73** [comment]
I solved. I don't use name field and now i can find correct sensor state.

![image](https://user-images.githubusercontent.com/16063061/71546292-b7477180-2995-11ea-9a4b-4d96ef2651dd.png)

Thanks.
