### ISSUE TITLE
Update to 46573 is still proposing into my home assistant but can't update

### ISSUE THREAD

**Issue by grayve** [doudz/homeassistant-myjdownloader#25]
Hello dear developers,

Since 2 days my home assistant is proposing me the update like following
![grafik](https://user-images.githubusercontent.com/31500977/186617971-bcdbd5c3-2082-46f9-8edb-d2e98cba3ad2.png)

I click on it and have
![grafik](https://user-images.githubusercontent.com/31500977/186618098-df8f79e8-1f4b-450a-8aa9-7f5cb798ce45.png)

Sadly if I want to update it I have this next screen:
![grafik](https://user-images.githubusercontent.com/31500977/186618162-e93d27ed-98c4-4a5b-83d9-10fa83525a84.png)
The message says that it's not available.

Then if I close the window it come back again. 

I tried to remove the integration from here:
![grafik](https://user-images.githubusercontent.com/31500977/186618316-c369775d-1677-46db-9087-a3096918ed62.png)

And re added but it seems that the update message is coming back anyway.

I do believe it's the second time it's happening with Myjdownloader updates to be kind of stucked on my config

I use a Odroid home assistant blue
With this configuration:
![grafik](https://user-images.githubusercontent.com/31500977/186618782-5a2f6b5d-1c64-409c-a4fb-253904a57aac.png)
(not sure what to show more to help on this topic. Let me know if you need more intel)

**Comment by Nyaran** [comment]
Here with same problem, but I think is not a problem on integration side, as if you access with MyJDownloader site and try to update, there is not update available, but if you check JDownloader site, it says the latest version is the one referenced by the integration.

**Comment by grayve** [comment]
update is not proposed anymore
