### ISSUE TITLE
Feature request: add service to allow adding new downloads 

### ISSUE THREAD

**Issue by jondycz** [doudz/homeassistant-myjdownloader#34]
I would love to be able to add new downloads to the queue using a text input entity in home assistant through a service call.

**Comment by iroQuai** [comment]
that would be wonderul. the transmission card (which looks pretty similar) has that option already!

**Comment by jondycz** [comment]
> that would be wonderul. the transmission card (which looks pretty similar) has that option already!

I know I PRed that change
