### ISSUE TITLE
Feature request: ETA

### ISSUE THREAD

**Issue by Sknny-T** [doudz/homeassistant-myjdownloader#35]
Would be nice to have a entity that shows the ETA time of the download.

**Comment by doudz** [comment]
since you can download many files at the same time ETA time would be the end of all downloads

**Comment by jondycz** [comment]
Then add the ability to list different downloads. The same way transmission integration does it

**Comment by oribafi** [comment]
The packages sensor (disabled by default) already has attributes that contain an `eta` attribute when downloads are running.
