### ISSUE TITLE
The 'links' sensor is not present

### ISSUE THREAD

**Issue by SzymaneKwr** [doudz/homeassistant-myjdownloader#36]
What is the reason that I can't display the list of links in the tab?
![2023-02-13_08h45_47](https://user-images.githubusercontent.com/77275930/218399883-9cf513d2-fe71-49a3-9194-99ced77872db.png)

**Comment by jondycz** [comment]
Where did you get this card? I don't have that option

**Comment by doudz** [comment]
You probably disable it.
Go to settings, devices and choose the myjdownloader device.
In the sensors panel check if the links sensor is disabled 
If necessary enable it in the advanced settings panel

**Comment by doudz** [comment]
![IMG_20230301_175743](https://user-images.githubusercontent.com/1262548/222209057-cb167b2d-2f81-4247-bdea-2251af399e74.jpg)

**Comment by SzymaneKwr** [comment]
> ![IMG_20230301_175743](https://user-images.githubusercontent.com/1262548/222209057-cb167b2d-2f81-4247-bdea-2251af399e74.jpg)



> You probably disable it. Go to settings, devices and choose the myjdownloader device. In the sensors panel check if the links sensor is disabled If necessary enable it in the advanced settings panel

Thank you very much. Works. It was actually in hidden entities.
