### ISSUE TITLE
Limit option

### ISSUE THREAD

**Issue by cagnulein** [doudz/homeassistant-myjdownloader#6]
Hi, could you please add the ability to write the LIMIT Bandwith parameter?
I would like to create an automation based on my presence at home (if i'm away, i could set no limit, if i'm home, i could set it to a minimium value...)

Thanks

**Comment by doudz** [comment]
It's possible but needs a bit of refactoring to add a service

**Comment by oribafi** [comment]
I'm currently rewriting this integration to provide this feature and others, like setup from the UI and starting/stopping of downloads: https://github.com/oribafi/homeassistant-myjdownloader/tree/rewrite

It's still in very early development but I'm grateful for any feedback and comments.

**Comment by oribafi** [comment]
I did a rewrite of the integration with that and other features here: https://github.com/oribafi/homeassistant-myjdownloader/tree/rewrite
It's still in early development, so I'm grateful for feedback and anyone willing to test. Thanks for this great integration, which motivated me to learn how to write integrations for HA!

**Comment by doudz** [comment]
Nice !
I'd be happy to test, and fill free to make PR to improve the current integration !

**Comment by oribafi** [comment]
Sure, let me know how it works for you! I opened a new issue to track progress on that here: https://github.com/doudz/homeassistant-myjdownloader/issues/12

If I remember correctly, wasn't this integration once part of Home Assistant Core? If so, was there a reason for removing it?

**Comment by doudz** [comment]
Done by @oribafi
