### ISSUE TITLE
Device not found

### ISSUE THREAD

**Issue by mariomare22** [doudz/homeassistant-myjdownloader#7]
Hello just installed and tried to configure it

```
 - platform: myjdownloader
    email: my@email.com
    password: mypassword
    name: JDownloader@ubuntu-server
    scan_interval: 5
```

But i got error `device not found`

**Comment by bcutter** [comment]
Where do you ge the "device not found" message?

**Comment by mariomare22** [comment]
Maybe I am doing something wrong in here

![image](https://user-images.githubusercontent.com/12135860/101544460-023f7680-39a6-11eb-87ea-d9b63ee800c8.png)

**Comment by bcutter** [comment]
Have a look at

https://github.com/doudz/homeassistant-myjdownloader/issues/1

https://github.com/doudz/homeassistant-myjdownloader/issues/2

They had the same issue and somehow fixed it.

**Comment by mariomare22** [comment]
If i remove the name I cannot find it at all.
I am using 44e5a45

**Comment by mariomare22** [comment]
Also, since i have added the sensor in configuration.yml
DNS requests to api.jdownloader.org are going CRAZY!
![image](https://user-images.githubusercontent.com/12135860/101767104-0f627f80-3ae4-11eb-88e3-f3e77ad22059.png)
![image](https://user-images.githubusercontent.com/12135860/101767155-1ee1c880-3ae4-11eb-8b36-3ad57da5e051.png)

**Comment by doudz** [comment]
You put scan interval to 5sec, this is probably the reason

**Comment by mariomare22** [comment]
I have removed.
How can I now add it to my lovelace?

**Comment by bcutter** [comment]
> Also, since i have added the sensor in configuration.yml
> 
> DNS requests to api.jdownloader.org are going CRAZY!
> 
> ![image](https://user-images.githubusercontent.com/12135860/101767104-0f627f80-3ae4-11eb-88e3-f3e77ad22059.png)
> 
> ![image](https://user-images.githubusercontent.com/12135860/101767155-1ee1c880-3ae4-11eb-8b36-3ad57da5e051.png)
> 
> 

Oh wow, you're absolutely right. Took a look at my DNS log too: 18 requests every minute (scan interval = 60 s). I think I'll kick the integration, for me it was just a test I have no real use-case for having those basic information (at the end of the day: status and bandwith) in Home Assistant.

**Comment by doudz** [comment]
Please try using new release 2.0
